2024-02-21 04:12:57,204 INFO    MainThread:10666 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-02-21 04:12:57,204 INFO    MainThread:10666 [wandb_setup.py:_flush():76] Configure stats pid to 10666
2024-02-21 04:12:57,204 INFO    MainThread:10666 [wandb_setup.py:_flush():76] Loading settings from /home/kjk/.config/wandb/settings
2024-02-21 04:12:57,204 INFO    MainThread:10666 [wandb_setup.py:_flush():76] Loading settings from /home/kjk/Documents/Workspace/NeuralNetfromScratch/src/models/wandb/settings
2024-02-21 04:12:57,204 INFO    MainThread:10666 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-21 04:12:57,204 INFO    MainThread:10666 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-21 04:12:57,204 INFO    MainThread:10666 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-21 04:12:57,205 INFO    MainThread:10666 [wandb_init.py:_log_setup():526] Logging user logs to /home/kjk/Documents/Workspace/NeuralNetfromScratch/src/models/wandb/run-20240221_041257-ptr49hky/logs/debug.log
2024-02-21 04:12:57,205 INFO    MainThread:10666 [wandb_init.py:_log_setup():527] Logging internal logs to /home/kjk/Documents/Workspace/NeuralNetfromScratch/src/models/wandb/run-20240221_041257-ptr49hky/logs/debug-internal.log
2024-02-21 04:12:57,205 INFO    MainThread:10666 [wandb_init.py:_jupyter_setup():472] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f4a903bea70>
2024-02-21 04:12:57,205 INFO    MainThread:10666 [wandb_init.py:init():566] calling init triggers
2024-02-21 04:12:57,205 INFO    MainThread:10666 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-02-21 04:12:57,205 INFO    MainThread:10666 [wandb_init.py:init():591] re-initializing run, found existing run on stack: et0c7tx4
2024-02-21 04:12:57,206 INFO    MainThread:10666 [wandb_run.py:_finish():1970] finishing run kimkj/mnist-model-evaluation/et0c7tx4
2024-02-21 04:12:57,206 INFO    MainThread:10666 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2024-02-21 04:12:57,206 INFO    MainThread:10666 [wandb_run.py:_restore():2193] restore
2024-02-21 04:12:57,206 INFO    MainThread:10666 [wandb_run.py:_restore():2199] restore done
2024-02-21 04:12:58,833 WARNING MsgRouterThr:10666 [router.py:message_loop():77] message_loop has been closed
2024-02-21 04:13:08,210 INFO    MainThread:10666 [wandb_run.py:_restore():2193] restore
2024-02-21 04:13:08,210 INFO    MainThread:10666 [wandb_run.py:_restore():2199] restore done
2024-02-21 04:13:08,272 ERROR   MainThread:10666 [wandb_init.py:init():1204] error
Traceback (most recent call last):
  File "/home/kjk/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2219, in _atexit_cleanup
    self._on_finish()
  File "/home/kjk/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2474, in _on_finish
    _ = exit_handle.wait(timeout=-1, on_progress=self._on_progress_exit)
  File "/home/kjk/.local/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 298, in wait
    on_probe(probe_handle)
  File "/home/kjk/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2436, in _on_probe_exit
    result = handle.wait(timeout=0, release=False)
  File "/home/kjk/.local/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 281, in wait
    raise MailboxError("transport failed")
wandb.sdk.lib.mailbox.MailboxError: transport failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kjk/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1176, in init
    run = wi.init()
  File "/home/kjk/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 601, in init
    latest_run.finish()
  File "/home/kjk/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 420, in wrapper
    return func(self, *args, **kwargs)
  File "/home/kjk/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 361, in wrapper
    return func(self, *args, **kwargs)
  File "/home/kjk/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1961, in finish
    return self._finish(exit_code, quiet)
  File "/home/kjk/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1976, in _finish
    self._atexit_cleanup(exit_code=exit_code)
  File "/home/kjk/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2230, in _atexit_cleanup
    self._backend.cleanup()
  File "/home/kjk/.local/lib/python3.10/site-packages/wandb/sdk/backend/backend.py", line 232, in cleanup
    self.interface.join()
  File "/home/kjk/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 547, in join
    super().join()
  File "/home/kjk/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 710, in join
    _ = self._communicate_shutdown()
  File "/home/kjk/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 440, in _communicate_shutdown
    _ = self._communicate(record)
  File "/home/kjk/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 300, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/kjk/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 60, in _communicate_async
    future = self._router.send_and_receive(rec, local=local)
  File "/home/kjk/.local/lib/python3.10/site-packages/wandb/sdk/interface/router.py", line 94, in send_and_receive
    self._send_message(rec)
  File "/home/kjk/.local/lib/python3.10/site-packages/wandb/sdk/interface/router_sock.py", line 36, in _send_message
    self._sock_client.send_record_communicate(record)
  File "/home/kjk/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 216, in send_record_communicate
    self.send_server_request(server_req)
  File "/home/kjk/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/home/kjk/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/kjk/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2024-02-21 04:13:16,861 INFO    MainThread:10666 [wandb_run.py:_finish():1970] finishing run kimkj/mnist-model-evaluation/et0c7tx4
2024-02-21 04:13:27,751 INFO    MainThread:10666 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-02-21 04:13:27,751 INFO    MainThread:10666 [wandb_setup.py:_flush():76] Configure stats pid to 10666
2024-02-21 04:13:27,751 INFO    MainThread:10666 [wandb_setup.py:_flush():76] Loading settings from /home/kjk/.config/wandb/settings
2024-02-21 04:13:27,751 INFO    MainThread:10666 [wandb_setup.py:_flush():76] Loading settings from /home/kjk/Documents/Workspace/NeuralNetfromScratch/src/models/wandb/settings
2024-02-21 04:13:27,751 INFO    MainThread:10666 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-21 04:13:27,751 INFO    MainThread:10666 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-21 04:13:27,751 INFO    MainThread:10666 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-21 04:13:27,751 INFO    MainThread:10666 [wandb_init.py:_log_setup():526] Logging user logs to /home/kjk/Documents/Workspace/NeuralNetfromScratch/src/models/wandb/run-20240221_041327-6t5arz35/logs/debug.log
2024-02-21 04:13:27,751 INFO    MainThread:10666 [wandb_init.py:_log_setup():527] Logging internal logs to /home/kjk/Documents/Workspace/NeuralNetfromScratch/src/models/wandb/run-20240221_041327-6t5arz35/logs/debug-internal.log
2024-02-21 04:13:27,751 INFO    MainThread:10666 [wandb_init.py:init():566] calling init triggers
2024-02-21 04:13:27,752 INFO    MainThread:10666 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-02-21 04:13:27,752 INFO    MainThread:10666 [wandb_init.py:init():616] starting backend
2024-02-21 04:13:27,752 INFO    MainThread:10666 [wandb_init.py:init():620] setting up manager
2024-02-21 04:13:27,810 ERROR   MainThread:10666 [wandb_init.py:init():1204] error
Traceback (most recent call last):
  File "/home/kjk/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1176, in init
    run = wi.init()
  File "/home/kjk/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 621, in init
    manager._inform_init(
  File "/home/kjk/.local/lib/python3.10/site-packages/wandb/sdk/wandb_manager.py", line 200, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "/home/kjk/.local/lib/python3.10/site-packages/wandb/sdk/service/service_sock.py", line 39, in _svc_inform_init
    self._sock_client.send(inform_init=inform_init)
  File "/home/kjk/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/home/kjk/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/home/kjk/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/kjk/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2024-02-21 04:13:28,682 INFO    MainThread:10666 [wandb_watch.py:watch():51] Watching
